-- Karlach verdict build (analysis/KARLACH_BEST_BUILD.md, model analysis/karlach_model.py), Builds.lua format.
-- Not merged: the main session adds it to BA.Builds and BA.Origins.karlach.
  {
    id = "throwthief", name = "Throwzerker Thief (Berserker 7 / Thief 3 / Fighter 2)", tier = "S+",
    role = "Thrower: 4 throws every turn, 2 of them knock Prone; Nyrulna blast on every throw",
    why = "Enraged Throw (Berserker) is a bonus action with no once-per-turn limit, and Thief's Fast Hands gives a second bonus action, so 2 throws from Extra Attack + 2 Enraged Throws every turn; each Enraged Throw knocks the target Prone. Tavern Brawler adds STR to every throw's attack and damage, Action Surge adds 2 more throws once per short rest. About 55% more sustained damage than Path of Giants 12 in Act 3 and 30% more than Berserker 10 / Fighter 2.",
    classes = { "Barbarian", "Rogue", "Fighter" }, start = "Barbarian",
    races = { "Zariel Tiefling", "Githyanki", "Duergar" },
    raceWhy = "Karlach is locked to Zariel Tiefling (fire resistance). Others: Githyanki Misty Step for throwing angles; Duergar Enlarge and Invisibility.",
    background = "Outlander (Karlach's own: Athletics, Survival)",
    base = { STR = 15, DEX = 14, CON = 15, INT = 8, WIS = 10, CHA = 8 }, plus2 = "STR", plus1 = "CON",
    skills = { "Athletics", "Intimidation", "Perception", "Sleight of Hand" },
    levels = {
      L("Barbarian", { "Rage, Unarmoured Defence", "Skills: Intimidation, Perception", "Weapon: two-handed melee until Tavern Brawler" }, { "Intimidation", "Perception" }),
      L("Barbarian", { "Reckless Attack, Danger Sense" }, {}),
      L("Barbarian", { "Subclass: Berserker (Frenzy, Frenzied Strike, Enraged Throw)" }, { "Berserker" }),
      L("Barbarian", { "Feat: Tavern Brawler, +1 Strength (STR 18)", "Weapon: Returning Pike (throw)" }, { "Tavern Brawler" }),
      L("Barbarian", { "Extra Attack, Fast Movement" }, {}),
      L("Rogue", { "Skill: Sleight of Hand", "Expertise: Athletics, Sleight of Hand" }, { "Sleight of Hand", "Athletics" }),
      L("Rogue", { "Cunning Action" }, {}),
      L("Rogue", { "Subclass: Thief (Fast Hands = second bonus action = second Enraged Throw)" }, { "Thief" }),
      L("Fighter", { "Fighting Style: Defence (+1 AC in armour)", "Second Wind" }, { "Defence" }),
      L("Fighter", { "Action Surge" }, {}),
      L("Barbarian", { "Mindless Rage" }, {}),
      L("Barbarian", { "Feral Instinct" }, {}),
    },
    gear = "Returning Pike -> Nyrulna + Viconia's Walking Fortress, Ring of Flinging, Gloves of Uninhibited Kushigo, Caustic Band, Horns of the Berserker, Armour of Agility or Bonespike Garb (never Helldusk Armour), Elixir of Cloud Giant Strength",
    note = "Respec Karlach with Withers (she stays a Zariel Tiefling). No heavy body armour: Helldusk Armour is Plate and switches off Rage damage, throw bonus and resistances. Nyrulna's 3d4 blast also hits allies and Karlach within 6 m of the target: throw from further away.",
  },
